name: CH

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0,6,12 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO }}
      RONGHUA_VIDEO2: ${{ secrets.RONGHUA_VIDEO2 }}
      RONGHUA_VIDEO3: ${{ secrets.RONGHUA_VIDEO3 }}
      RONGHUA_VIDEO4: ${{ secrets.RONGHUA_VIDEO4 }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【CH1】'
        if: env.RONGHUA_VIDEO
        run: |
          node Task/RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO }}

      - name: '运行 【CH2】'
        if: env.RONGHUA_VIDEO2
        run: |
          node Task/RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO2 }}

      - name: '运行 【CH3】'
        if: env.RONGHUA_VIDEO3
        run: |
          node Task/RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO3 }}

      - name: '运行 【CH4】'
        if: env.RONGHUA_VIDEO4
        run: |
          node Task/RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO4 }}
